version: '3'
services:
  mongo:
    image: mongo:4.2
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "./data/dump:/dump"
      - "./data/mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh"
  dashboard:
    build: ./dashboard
    restart: always
    hostname: dashboard
    environment:
      - BACKEND_PASSWORD=changemenow
    ports:
      - "80:3000"
  api:
    build: ./api
    hostname: api
    restart: always
    ports:
      - "4040:4040"
    links:
      - mongo
    volumes:
      - "./agent:/agent"
    environment:
      - BACKEND_PASSWORD=changemenow